apiVersion: v1
kind: ConfigMap
metadata:
  name: swagger-config
data:
  swagger.json: |
    {
      "openapi": "3.0.0",
      "info": {
        "version": "1.0.0",
        "title": "Your API",
        "description": "Your API description"
      },
      "paths": {
        "/sample-path": {
          "get": {
            "summary": "Sample Endpoint",
            "responses": {
              "200": {
                "description": "Successful response",
                "content": {
                  "application/json": {
                    "schema": {
                      "type": "object",
                      "properties": {
                        "message": {
                          "type": "string"
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }

